### ISSUE TITLE
Remove Debug keys from genconfig

### ISSUE THREAD

**Issue by sbc64** [hashcloak/genconfig#2]
The current config files generate by this script include a [Debug] Section that seems to break mixnet configuration because the wallet demo times out.

```toml
[Debug]
  NumSphinxWorkers = 8
  NumProviderWorkers = 1
  NumKaetzchenWorkers = 3
  SchedulerExternalMemoryQueue = false
  SchedulerQueueSize = 0
  SchedulerMaxBurst = 16
  UnwrapDelay = 10
  ProviderDelay = 500
  KaetzchenDelay = 750
  SchedulerSlack = 10
  SendSlack = 50
  DecoySlack = 15000
  ConnectTimeout = 60000
  HandshakeTimeout = 30000
  ReauthInterval = 30000
  SendDecoyTraffic = false
  DisableRateLimit = true
  GenerateOnly = false
```

1. Remove the Debug parameters from the genconfig (this is what I currently do but manually). The only rule I leave is `DisableRateLimit`.
2. Determine the parameter that forces the timeout
